/* @macrome
 * @generatedby @bablr/macrome-generator-bablr
 * @generatedfrom ./grammar.macro.js#774adf93591a173ae8d3927396a65057e1dabfb5
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import _applyDecs from "@babel/runtime/helpers/applyDecs2305";
var _literalMixin;
let _initProto, _IdentifierDecs, _ListDecs, _KeywordDecs, _LiteralDecs, _PunctuatorDecs, _AnyDecs, _SpaceDecs, _AllDecs, _OptionalDecs;
import { spam as m } from '@bablr/boot';
import { Node, InjectFrom, AllowEmpty, CoveredBy } from '@bablr/helpers/decorators';
import { eat, eatMatch, o, shiftMatch, fail } from '@bablr/helpers/grammar';
import { triviaEnhancer } from '@bablr/helpers/trivia';
import * as productions from '@bablr/helpers/productions';
import { mixin as functionMixin } from './mixins/function.js';
import { mixin as statementMixin } from './mixins/statement.js';
import { mixin as callMixin } from './mixins/call.js';
import { mixin as literalMixin } from './mixins/literals.js';
import * as Regex from './regex.js';
export const dependencies = {
  Regex
};
export const canonicalURL = 'https://bablr.org/languages/universe/ruby';
export const defaultMatcher = m`.+: <_Expression />`;
let reservedWords = new Set(['BEGIN', 'class', 'ensure', 'nil', 'self', 'when', 'END', 'def', 'false', 'not', 'super', 'while', 'true', 'begin', 'else', 'in', 'rescue', 'ndef', 'break', 'elsif', 'module', 'retry', 'unless', 'case', 'end', 'next', 'return', 'until']);
export const atrivialGrammar = class RubyGrammar extends (_literalMixin = literalMixin(functionMixin(statementMixin(callMixin(Object))))) {
  static {
    [_initProto] = _applyDecs(this, [[[AllowEmpty, Node], 2, "Program"], [_IdentifierDecs, 2, "Identifier"], [_ListDecs, 2, "List"], [_KeywordDecs, 2, "Keyword"], [_LiteralDecs, 2, "Literal"], [_PunctuatorDecs, 2, "Punctuator"], [_AnyDecs, 2, "Any"], [_SpaceDecs, 2, "Space"], [_AllDecs, 2, "All"], [_OptionalDecs, 2, "Optional"]], [], 0, void 0, _literalMixin).e;
  }
  constructor(...args) {
    super(...args);
    _initProto(this);
  }
  *[(_IdentifierDecs = [CoveredBy('Expression'), Node], _ListDecs = [AllowEmpty, InjectFrom(productions)], _KeywordDecs = [Node, InjectFrom(productions)], _LiteralDecs = [Node, InjectFrom(productions)], _PunctuatorDecs = [Node, InjectFrom(productions)], _AnyDecs = InjectFrom(productions), _SpaceDecs = InjectFrom(productions), _AllDecs = InjectFrom(productions), _OptionalDecs = [AllowEmpty, InjectFrom(productions)], Symbol.for('@bablr/fragment'))]({
    props: {
      rootMatcher
    }
  }) {
    // needed for the trivia plugin
    yield eat(rootMatcher);
  }
  *Program() {
    yield eat(m`statements[]: <__Statements />`);
  }
  *Expression({
    props: {
      power = 34
    },
    s
  }) {
    let res;
    if (!s.holding) {
      if (res = yield eatMatch(m`<_LiteralExpression />`)) {} else if (power >= 4 && (res = yield eatMatch(m`<UnaryCall /|\+|!|~|/ />`))) {} else if (power >= 4 && (res = yield eatMatch(m`<NewExpression 'new' />`, o({
        power
      })))) {} else if (res = yield eatMatch(m`<Identifier />`)) {}
    } else {
      res = yield eatMatch(m`<__Call />`, o({
        power
      }));
    }
    if (res) {
      return shiftMatch(m`<_Expression />`, o({
        power
      }));
    }
  }
  *Identifier({
    ctx
  }) {
    let id = ctx.sourceTextFor(yield eat(m`value: <*Literal /[a-zA-Z_$][a-zA-Z\d_$]*/ />`));
    if (reservedWords.has(id)) yield fail();
  }
  *List() {}
  *Keyword() {}
  *Literal() {}
  *Punctuator() {}
  *Any() {}
  *Space() {}
  *All() {}
  *Optional() {}
};
export const grammar = triviaEnhancer({
  triviaIsAllowed: s => s.span === 'Bare',
  triviaMatcher: m`#: <*_Space /[ \t]/ />`
}, atrivialGrammar);