/* @macrome
 * @generatedby @bablr/macrome-generator-bablr
 * @generatedfrom ./regex.macro.js#08fcc72e220e1d46a79ac581f09305bdf4a24b35
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import _applyDecs from "@babel/runtime/helpers/applyDecs2305";
let _initProto, _FlagsDecs, _GroupDecs, _LookaheadGroupDecs, _AssertionDecs, _StartOfInputAssertionDecs, _EndOfInputAssertionDecs, _WordBoundaryAssertionDecs, _CharacterDecs, _CharacterClassDecs, _CharacterClassRangeDecs, _CharacterSetDecs, _AnyCharacterSetDecs, _DigitCharacterSetDecs, _SpaceCharacterSetDecs, _WordCharacterSetDecs, _QuantifierDecs, _AnyDecs, _KeywordDecs, _PunctuatorDecs;
import { re, spam as m } from '@bablr/boot';
import { Node, CoveredBy, InjectFrom, UndefinedAttributes, AllowEmpty } from '@bablr/helpers/decorators';
import objectEntries from 'iter-tools-es/methods/object-entries';
import * as Shared from '@bablr/helpers/productions';
import { eat, eatMatch, match, holdForMatch, guard, defineAttribute, fail } from '@bablr/helpers/grammar';
import { buildString, buildBoolean } from '@bablr/helpers/builders';
export const canonicalURL = 'https://bablr.org/languages/core/universe/es3-regex-pattern';
export const dependencies = {};
const escapables = new Map(objectEntries({
  f: '\f',
  n: '\n',
  r: '\r',
  t: '\t',
  v: '\v'
}));
const flagCharacters = {
  global: 'g',
  ignoreCase: 'i',
  multiline: 'm'
};
const unique = flags => flags.length === new Set(flags).size;
const getSpecialPattern = span => {
  if (span === 'Pattern') {
    return re`/[*+{}[\]().^$|\n\\]/`;
  } else if (span === 'CharacterClass') {
    return re`/[\]\\]/`;
  } else {
    throw new Error('unknown span type for special pattern');
  }
};
export const grammar = class RegexGrammar {
  static {
    [_initProto] = _applyDecs(this, [[Node, 2, "Pattern"], [_FlagsDecs, 2, "Flags"], [AllowEmpty, 2, "Alternatives"], [[AllowEmpty, Node], 2, "Alternative"], [AllowEmpty, 2, "Elements"], [_GroupDecs, 2, "Group"], [Node, 2, "CapturingGroup"], [_LookaheadGroupDecs, 2, "LookaheadGroup"], [_AssertionDecs, 2, "Assertion"], [_StartOfInputAssertionDecs, 2, "StartOfInputAssertion"], [_EndOfInputAssertionDecs, 2, "EndOfInputAssertion"], [_WordBoundaryAssertionDecs, 2, "WordBoundaryAssertion"], [_CharacterDecs, 2, "Character"], [Node, 2, "Literal"], [_CharacterClassDecs, 2, "CharacterClass"], [_CharacterClassRangeDecs, 2, "CharacterClassRange"], [_CharacterSetDecs, 2, "CharacterSet"], [_AnyCharacterSetDecs, 2, "AnyCharacterSet"], [_DigitCharacterSetDecs, 2, "DigitCharacterSet"], [_SpaceCharacterSetDecs, 2, "SpaceCharacterSet"], [_WordCharacterSetDecs, 2, "WordCharacterSet"], [_QuantifierDecs, 2, "Quantifier"], [Node, 2, "UnsignedInteger"], [Node, 2, "EscapeSequence"], [Node, 2, "EscapeCode"], [Node, 2, "Digit"], [_AnyDecs, 2, "Any"], [_KeywordDecs, 2, "Keyword"], [_PunctuatorDecs, 2, "Punctuator"]], []).e;
  }
  constructor() {
    _initProto(this);
  }
  *[(_FlagsDecs = [UndefinedAttributes(Object.keys(flagCharacters)), AllowEmpty, Node], _GroupDecs = [CoveredBy('Element'), Node], _LookaheadGroupDecs = [UndefinedAttributes('negate'), Node], _AssertionDecs = CoveredBy('Element'), _StartOfInputAssertionDecs = [CoveredBy('Assertion'), Node], _EndOfInputAssertionDecs = [CoveredBy('Assertion'), Node], _WordBoundaryAssertionDecs = [UndefinedAttributes(['negate']), CoveredBy('Assertion'), Node], _CharacterDecs = [CoveredBy('Element'), CoveredBy('CharacterClassElement'), Node], _CharacterClassDecs = [UndefinedAttributes(['negate']), CoveredBy('Element'), Node], _CharacterClassRangeDecs = [CoveredBy('CharacterClassElement'), Node], _CharacterSetDecs = CoveredBy('Element'), _AnyCharacterSetDecs = [CoveredBy('CharacterSet'), Node], _DigitCharacterSetDecs = [UndefinedAttributes(['negate']), CoveredBy('CharacterSet'), Node], _SpaceCharacterSetDecs = [UndefinedAttributes(['negate']), CoveredBy('CharacterSet'), Node], _WordCharacterSetDecs = [UndefinedAttributes(['negate']), CoveredBy('CharacterSet'), Node], _QuantifierDecs = [UndefinedAttributes(['min', 'max']), Node], _AnyDecs = InjectFrom(Shared), _KeywordDecs = [Node, InjectFrom(Shared)], _PunctuatorDecs = [Node, InjectFrom(Shared)], "Pattern")]() {
    yield eat(m`openToken: <*Punctuator '/' { balanced: '/', balancedSpan: 'Pattern' } />`);
    yield eat(m`<Alternatives />`);
    yield eat(m`closeToken: <*Punctuator '/' { balancer: true } />`);
    yield eat(m`flags$: <Flags />`);
  }
  *Flags({
    ctx
  }) {
    const flags = yield match(re`/[gim]+/`);
    const flagsStr = ctx.sourceTextFor(flags) || '';
    if (flagsStr && !unique(flagsStr)) throw new Error('flags must be unique');
    for (const {
      0: name,
      1: chr
    } of Object.entries(flagCharacters)) {
      if (flagsStr.includes(chr)) {
        yield defineAttribute(name, true);
      } else {
        yield defineAttribute(name, false);
      }
    }
    for (const flagChr of flagsStr) {
      yield eat(m`tokens[]: <*Keyword ${buildString(flagChr)} />`);
    }
  }
  *Alternatives() {
    do {
      yield eat(m`alternatives[]$: <Alternative />`);
    } while (yield eatMatch(m`separatorTokens[]: <*Punctuator '|' />`));
  }
  *Alternative() {
    yield eat(m`elements[]$: <Elements />`);
  }
  *Elements() {
    yield eat(m`.[]+: []`);
    while (yield match(re`/[^|]/`)) {
      yield eat(m`.[]+: <__Element />`);
    }
  }
  *Element() {
    yield guard(m`<*Keyword /[*+?]/ />`);
    yield eat(m`<_Any />`, [m`<CharacterClass '[' />`, m`<Group '(?:' />`, m`<Assertion /[$^]|\\b/i />`, m`<CharacterSet /\.|\\[dswp]/i />`, m`<Character />`]);
    if (yield match(re`/[*+?{]/`)) {
      return holdForMatch(m`<Quantifier />`);
    }
  }
  *Group() {
    yield eat(m`openToken: <*Punctuator '(?:' { balanced: ')' } />`);
    yield eat(m`<Alternatives />`);
    yield eat(m`closeToken: <*Punctuator ')' { balancer: true } />`);
  }
  *CapturingGroup() {
    yield eat(m`openToken: <*Punctuator '(' { balanced: ')' } />`);
    yield eat(m`<Alternatives />`);
    yield eat(m`closeToken: <*Punctuator ')' { balancer: true } />`);
  }
  *LookaheadGroup() {
    yield eat(m`openToken: <*Punctuator '(?' { balanced: ')' } />`);
    yield eat(m`negateToken: <*Punctuator /[!=]/ />`);
    yield eat(m`<Alternatives />`);
    yield eat(m`closeToken: <*Punctuator ')' { balancer: true } />`);
  }
  *Assertion() {
    yield eat(m`<_Any />`, [m`<*StartOfInputAssertion '^' />`, m`<*EndOfInputAssertion '$' />`, m`<*WordBoundaryAssertion /\\b/i />`]);
  }
  *StartOfInputAssertion() {
    yield eat(m`sigilToken: <*Keyword '^' />`);
  }
  *EndOfInputAssertion() {
    yield eatMatch(m`sigilToken: <*Keyword '$' />`);
  }
  *WordBoundaryAssertion({
    ctx
  }) {
    yield eatMatch(m`escapeToken: <*Punctuator '\\' />`);
    const m_ = yield eat(m`value: <*Keyword /b/i />`);
    yield defineAttribute('negate', buildBoolean(ctx.sourceTextFor(m_) === 'B'));
  }
  *Character() {
    yield eat(m`value: <*Literal />`);
  }
  *Literal() {
    if (yield match('\\')) {
      yield eat(m`@: <EscapeSequence />`);
    } else {
      yield eat(re`/[^\r\n\t]/`);
    }
  }
  *CharacterClass() {
    yield eat(m`openToken: <*Punctuator '[' { balancedSpan: 'CharacterClass', balanced: ']' } />`);
    let negate = yield eatMatch(m`negateToken: <*Keyword '^' />`);
    yield defineAttribute('negate', !!negate);
    while (yield match(re`/./s`)) {
      yield eat(m`elements[]+$: <CharacterClassElement />`);
    }
    yield eat(m`closeToken: <*Punctuator ']' { balancer: true } />`);
  }
  *CharacterClassElement() {
    yield eat(m`<_Any />`, [m`<CharacterSet /\\[dswp]/i />`, m`<Gap '\\g' />`, m`<*Character />`]);
    if (yield match('-')) {
      return holdForMatch(m`<CharacterClassRange />`);
    }
  }
  *CharacterClassRange() {
    yield eat(m`min+$: <*Character />`);
    yield eat(m`sigilToken: <*Punctuator '-' />`);
    yield eat(m`max+$: <*Character />`);
  }
  *CharacterSet() {
    yield eat(m`<_Any />`, [m`<AnyCharacterSet '.' />`, m`<DigitCharacterSet /\\[dD]/  />`, m`<SpaceCharacterSet /\\[sS]/  />`, m`<WordCharacterSet /\\[wW]/  />`]);
  }
  *AnyCharacterSet() {
    yield eat(m`sigilToken: <*Keyword '.' />`);
  }
  *DigitCharacterSet({
    ctx
  }) {
    yield eat(m`escapeToken: <*Punctuator '\\' />`);
    let code = yield eat(m`value: <*Keyword /[dD]/ />`);
    yield defineAttribute('negate', buildBoolean(ctx.sourceTextFor(code) === 'D'));
  }
  *SpaceCharacterSet({
    ctx
  }) {
    yield eat(m`escapeToken: <*Punctuator '\\' />`);
    let code = yield eat(m`value: <*Keyword /[sS]/ />`);
    yield defineAttribute('negate', buildBoolean(ctx.sourceTextFor(code) === 'S'));
  }
  *WordCharacterSet({
    ctx
  }) {
    yield eat(m`escapeToken: <*Punctuator '\\' />`);
    let code = yield eat(m`value: <*Keyword /[wW]/ />`);
    yield defineAttribute('negate', ctx.sourceTextFor(code) === 'W');
  }
  *Quantifier({
    ctx
  }) {
    yield eat(m`element+$: <Element />`);
    let attrs, sigil;
    if (sigil = yield eatMatch(m`sigilToken: <*Keyword /[*+?]/ />`)) {
      switch (ctx.sourceTextFor(sigil)) {
        case '*':
          attrs = {
            min: 0,
            max: Infinity
          };
          break;
        case '+':
          attrs = {
            min: 1,
            max: Infinity
          };
          break;
        case '?':
          attrs = {
            min: 0,
            max: 1
          };
          break;
      }
    } else if (yield eat(m`openToken: <*Punctuator '{' { balanced: '}' } />`)) {
      let max;
      let min = yield eat(m`min$: <*UnsignedInteger />`);
      if (yield eatMatch(m`separator: <*Punctuator ',' />`)) {
        max = yield eatMatch(m`max$: <*UnsignedInteger />`);
      }
      min = min && ctx.sourceTextFor(min);
      max = max && ctx.sourceTextFor(max);
      min = min && parseInt(min, 10);
      max = max && parseInt(max, 10);
      attrs = {
        min,
        max
      };
      yield eat(m`closeToken: <*Punctuator '}' { balancer: true } />`);
    }
    yield defineAttribute('min', attrs.min);
    yield defineAttribute('max', attrs.max);
  }
  *UnsignedInteger() {
    yield eat(re`/\d+/`);
  }
  *EscapeSequence({
    state,
    ctx
  }) {
    const parentSpan = state.span;
    yield eat(m`escape: <*Punctuator '\\' { openSpan: 'Escape' } />`);
    let m_;
    let cooked;
    if (m_ = yield match(re`/[\\/fnrtv]/`)) {
      const match_ = ctx.sourceTextFor(m_);
      yield eat(m`code: <*Keyword ${buildString(match_)} { closeSpan: 'Escape' } />`);
      cooked = escapables.get(match_);
    } else if (m_ = yield match(getSpecialPattern(parentSpan))) {
      const match_ = ctx.sourceTextFor(m_);
      yield eat(m`code: <*Keyword ${buildString(match_)} { closeSpan: 'Escape' } />`);
      cooked = match_;
    } else if (yield match('x')) {
      let code = yield eat(m`code: <EscapeCode { closeSpan: 'Escape' } />`);
      cooked = String.fromCodePoint(parseInt(ctx.sourceTextFor(code.get('value')), 16));
    } else {
      yield fail();
    }
    yield defineAttribute('cooked', cooked);
  }
  *EscapeCode() {
    if (yield eatMatch(m`type: <*Keyword 'x' />`)) {
      yield eat(m`openToken: null`);
      yield eat(m`value$: <*UnsignedInteger /\d{2}/ />`);
      yield eat(m`closeToken: null`);
    }
  }
  *Digits() {
    while (yield eatMatch(m`<*Digit />`));
  }
  *Digit() {
    yield eat(re`/\d/`);
  }
  *Any() {}
  *Keyword() {}
  *Punctuator() {}
};