/* @macrome
 * @generatedby @bablr/macrome-generator-bablr
 * @generatedfrom ./call.macro.js#30639b67521fdcb03ef741537ce9d0bd15329c06
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import _applyDecs from "@babel/runtime/helpers/applyDecs2305";
import { getRoot } from '@bablr/agast-helpers/tree';
import { buildPattern, buildAlternative, buildAlternatives, buildElements } from '@bablr/helpers/builders';
import { spam as m, buildTag, re } from '@bablr/boot';
import * as regexLang from '@bablr/boot/languages/regex';
import { defineAttribute, eat, eatMatch, fail, match, o } from '@bablr/helpers/grammar';
import { UndefinedAttributes, Node, CoveredBy } from '@bablr/helpers/decorators';
import { buildEmbeddedRegex } from '@bablr/agast-vm-helpers/builders';
export const reTok_ = buildTag(regexLang, 'Pattern');
export const reTok = new Proxy(reTok_, {
  apply(tag, _, args) {
    return buildEmbeddedRegex(tag(...args));
  }
});

// 17 comma
// 16 assignment
// 15 logical OR
// 14 logical AND
// 13 bitwise OR
// 12 bitwise XOR
// 11 bitwise AND
// 10 equality
// 9 relational
// 8 bitwise shift
// 7 add/sub
// 6 mul/div
// 5 unary prefix
// 4 unary postfix
// 3 call
// 2 new
// 1 access

// problem: the concrete syntax is only right in some contexts (spans)
const escaped = {
  '\\': reTok.Character`\\`,
  '/': reTok.Character`\/`,
  '(': reTok.Character`\(`,
  ')': reTok.Character`\)`,
  '{': reTok.Character`\{`,
  '}': reTok.Character`\}`,
  '+': reTok.Character`\+`,
  '*': reTok.Character`\*`,
  '<': reTok.Character`\<`,
  '>': reTok.Character`\>`,
  '^': reTok.Character`\^`,
  '|': reTok.Character`\|`
};
const buildOperatorPattern = categories => buildPattern(buildAlternatives(categories.flatMap(operators => operators.map(op => buildAlternative(buildElements([...op].map(chr => {
  if ('\\/(){}+*^$?|<>'.includes(chr)) {
    return getRoot(escaped[chr]);
  } else {
    return getRoot(reTok.Character({
      raw: [chr]
    }));
  }
})))))));
const assignmentOperators = ['=', '+=', '-=', '*=', '/=', '%=', '<<=', '>>=', '>>>=', '&=', '^=', '|='];
const assignmentOperatorPattern = buildOperatorPattern([assignmentOperators]);
const unaryPrefixOperators = ['+', '-', '!', '~'];
const unaryPrefixOperatorPattern = buildOperatorPattern([unaryPrefixOperators]);
const unaryPostfixOperators = ['++', '--'];
const unaryPostfixOperatorPattern = buildOperatorPattern([unaryPostfixOperators]);
const binaryExpressionPowerRank = [['||'], ['&&'], ['|'], ['^'], ['&'], ['==', '!='], ['<=', '<', '>=', '>', 'instanceof', 'in'], ['>>>', '<<', '>>'], ['+', '-'], ['%', '*', '/']];
export const getBinaryOperatorPattern = power => {
  return buildOperatorPattern(binaryExpressionPowerRank.slice(Math.max(0, (30 - power) / 2 - 1)));
};
const getBinaryOperatorPower = str => {
  let idx = binaryExpressionPowerRank.findIndex(arr => arr.includes(str));
  return idx >= 0 ? (15 - idx) * 2 : null;
};
export const mixin = Base => {
  let _initProto, _UnaryCallDecs, _MethodCallDecs, _BinaryCallDecs, _AssignmentCallDecs, _MemberCallDecs, _CommaCallDecs;
  return class RubyCallGrammar extends Base {
    static {
      [_initProto] = _applyDecs(this, [[_UnaryCallDecs, 2, "UnaryCall"], [_MethodCallDecs, 2, "MethodCall"], [_BinaryCallDecs, 2, "BinaryCall"], [_AssignmentCallDecs, 2, "AssignmentCall"], [_MemberCallDecs, 2, "MemberCall"], [_CommaCallDecs, 2, "CommaCall"]], [], 0, void 0, Base).e;
    }
    constructor(...args) {
      super(...args);
      _initProto(this);
    }
    *[(_UnaryCallDecs = [UndefinedAttributes(['power', 'position']), CoveredBy('Expression'), CoveredBy('Call'), Node], _MethodCallDecs = [UndefinedAttributes(['power']), CoveredBy('Expression'), Node], _BinaryCallDecs = [UndefinedAttributes(['power']), CoveredBy('Expression'), CoveredBy('Call'), Node], _AssignmentCallDecs = [UndefinedAttributes(['power']), CoveredBy('Expression'), CoveredBy('Call'), Node], _MemberCallDecs = [UndefinedAttributes(['power']), CoveredBy('Expression'), CoveredBy('Call'), Node], _CommaCallDecs = [UndefinedAttributes(['power']), CoveredBy('Expression'), Node], "Call")]({
      props: {
        power = 34
      },
      ctx
    }) {
      let res;
      if (power >= 2 && (yield match(re`/\g[[.]/`))) {
        res = yield eat(m`<MemberCall />`, o({
          power
        }));
      }
      if (!res && power >= 6) {
        res = yield eatMatch(m`<MethodCall />`, o({
          power
        }));
      }
      if (!res && power >= 8 && (yield match(re`/[+-~!]/`))) {
        res = yield eat(m`<UnaryCall />`, o({
          power
        }));
      }
      if (!res && power >= 12) {
        res = yield eatMatch(m`<BinaryCall />`, o({
          power
        }));
      }
      if (!res && power >= 32) {
        if (res = yield eatMatch(m`<AssignmentCall/>`, o({
          power
        }))) {}
      }
      if (!res && power >= 34) {
        res = yield eatMatch(m`<CommaCall />`, o({
          power
        }));
      }
      const opPower = res && ctx.sourceTextFor(res.get('sigilToken'));
    }
    *UnaryCall({
      props: {
        power
      },
      s
    }) {
      let ownPower = 0;
      let op;
      if (!s.holding) {
        yield eatMatch(m`argument+$: null`);
        op = yield eatMatch(m`sigilToken: <*Punctuator ${unaryPrefixOperatorPattern} />`);
      }
      if (op) ownPower = 10;
      yield eat(m`argument+$: <__Expression />`, o({
        power: ownPower - 2
      }));
      if (!op) {
        yield eat(m`sigilToken: <*Punctuator ${unaryPostfixOperatorPattern} />`);
        ownPower = 12;
      }
      if (ownPower > power) yield fail();
      yield defineAttribute('power', ownPower);
      yield defineAttribute('position', op ? 'prefix' : 'suffix');
    }
    *MethodCall() {
      yield eat(m`callee+$: <__Expression />`, o({
        power: 4
      }));
      yield defineAttribute('power', 6);
      yield eat(m`openArgumentsToken: <*Punctuator '(' { balanced: ')' } />`);
      yield eat(m`arguments[]+: <_List />`, o({
        element: m`<Identifier />`,
        allowTrailingSeparator: false,
        separator: m`separatorTokens[]: <*Punctuator ',' />`
      }));
      yield eat(m`closeArgumentsToken: <*Punctuator ')' { balancer: true } />`);
    }
    *BinaryCall({
      props: {
        power
      },
      ctx
    }) {
      yield eat(m`left+$: <__Expression />`, o({
        power: power - 2
      }));
      let op = yield eat(m`sigilToken: <*Punctuator ${getBinaryOperatorPattern(power)} />`);
      let ownPower = getBinaryOperatorPower(ctx.sourceTextFor(op));
      yield eat(m`right+$: <__Expression />`, o({
        power: ownPower - 2
      }));
      yield defineAttribute('power', ownPower);
    }
    *AssignmentCall() {
      let lhs = yield eat(m`left+$: <__Expression />`, o({
        power: 2
      }));
      yield defineAttribute('power', 32);
      if (!['MemberExpression', 'Identifier'].includes(lhs.type.description)) {
        yield fail();
      }
      yield eat(m`sigilToken: <*Punctuator ${assignmentOperatorPattern} />`);
      yield eat(m`right+$: <__Expression />`, o({
        power: 30
      }));
    }
    *MemberCall({
      ctx
    }) {
      yield eat(m`object+$: <__Expression />`, o({
        power: 2
      }));
      yield defineAttribute('power', 2);
      let sigil = yield match(re`/[[.]/`);
      switch (ctx.sourceTextFor(sigil)) {
        case '.':
          {
            yield eat(m`operatorToken: <*Punctuator '.' />`);
            yield eat(m`property+$: <__Expression />`, o({
              power: 2
            }));
            yield eat(m`matchingSigilToken: null`);
            break;
          }
        case '[':
          {
            yield eat(m`operatorToken: <*Punctuator '[' { balanced: ']' } />`);
            yield eat(m`property+$: <__Expression />`);
            yield eat(m`matchingSigilToken: <*Punctuator ']' { balancer: true } />`);
            break;
          }
        default:
          yield fail();
      }
    }
    *CommaCall() {
      let count = 0;
      do {
        yield eatMatch(m`elements[]+$: <__Expression />`, o({
          power: 32
        }));
        count++;
        if (!count) {
          yield defineAttribute('power', 34);
        }
      } while (yield eatMatch(m`separatorTokens[]: <*Punctuator ',' />`));
      if (count === 1) yield fail();
    }
  };
};