/* @macrome
 * @generatedby @bablr/macrome-generator-bablr
 * @generatedfrom ./function.macro.js#99cb0a778d43bbfc95c2aaf67a791f5295fa282c
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import _applyDecs from "@babel/runtime/helpers/applyDecs2305";
import { spam as m } from '@bablr/boot';
import { defineAttribute, eat, eatMatch, o } from '@bablr/helpers/grammar';
import { CoveredBy, Node, UndefinedAttributes } from '@bablr/helpers/decorators';
export const mixin = Base => {
  let _initProto, _NewExpressionDecs;
  return class RubyFunctionGrammar extends Base {
    static {
      [_initProto] = _applyDecs(this, [[_NewExpressionDecs, 2, "NewExpression"]], [], 0, void 0, Base).e;
    }
    constructor(...args) {
      super(...args);
      _initProto(this);
    }
    *[(_NewExpressionDecs = [UndefinedAttributes(['power']), CoveredBy('Expression'), Node], "NewExpression")]({
      props: {
        power
      }
    }) {
      yield eat(m`sigilToken: <*Keyword 'new' />`);
      yield eat(m`callee+$: <_Expression />`, o({
        power: 4
      }));
      let p = yield power >= 4 ? eatMatch(m`openArgumentsToken: <*Punctuator '(' { balanced: ')' } />`) : eat(m`openArgumentsToken: <*Punctuator '(' { balanced: ')' } />`);
      if (p) {
        yield eat(m`arguments[]: <__List />`, o({
          element: m`<Identifier />`,
          allowTrailingSeparator: false,
          separator: m`separatorTokens[]: <*Punctuator ',' />`
        }));
        yield eat(m`closeArgumentsToken: <*Punctuator ')' { balancer: true } />`);
        yield defineAttribute('power', 2);
      } else {
        yield eat(m`arguments[]: []`);
        yield eat(m`separatorTokens[]: []`);
        yield eat(m`closeArgumentsToken: null`);
        yield defineAttribute('power', 4);
      }
    }
  };
};