/* @macrome
 * @generatedby @bablr/macrome-generator-bablr
 * @generatedfrom ./literals.macro.js#cd1a670e43882fe7637b19943e100324bf52f602
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import _applyDecs from "@babel/runtime/helpers/applyDecs2305";
import { re, spam as m } from '@bablr/boot';
import { eat, match, eatMatch, fail, o, defineAttribute } from '@bablr/helpers/grammar';
import { Node, CoveredBy, AllowEmpty } from '@bablr/helpers/decorators';
import { buildString } from '@bablr/helpers/builders';
export const escapables = new Map(Object.entries({
  b: '\b',
  f: '\f',
  n: '\n',
  r: '\r',
  t: '\t',
  0: '\0',
  '\\': '\\',
  '/': '/'
}));
export const mixin = Base => {
  let _initProto, _TrueDecs, _FalseDecs, _NilDecs, _ArrayDecs, _ObjectDecs, _StringDecs, _InfinityDecs, _IntegerDecs, _FloatDecs;
  return class RubyLiteralsGrammar extends Base {
    static {
      [_initProto] = _applyDecs(this, [[_TrueDecs, 2, "True"], [_FalseDecs, 2, "False"], [_NilDecs, 2, "Nil"], [_ArrayDecs, 2, "Array"], [_ObjectDecs, 2, "Object"], [Node, 2, "Property"], [_StringDecs, 2, "String"], [[AllowEmpty, Node], 2, "StringContent"], [Node, 2, "EscapeSequence"], [Node, 2, "EscapeCode"], [_InfinityDecs, 2, "Infinity"], [_IntegerDecs, 2, "Integer"], [_FloatDecs, 2, "Float"]], [], 0, void 0, Base).e;
    }
    constructor(...args) {
      super(...args);
      _initProto(this);
    }
    *[(_TrueDecs = [CoveredBy('LiteralExpression'), CoveredBy('Expression'), Node], _FalseDecs = [CoveredBy('LiteralExpression'), CoveredBy('Expression'), Node], _NilDecs = [CoveredBy('LiteralExpression'), CoveredBy('Expression'), Node], _ArrayDecs = [CoveredBy('LiteralExpression'), CoveredBy('Expression'), Node], _ObjectDecs = [CoveredBy('LiteralExpression'), CoveredBy('Expression'), Node], _StringDecs = [CoveredBy('LiteralExpression'), CoveredBy('Expression'), Node], _InfinityDecs = [CoveredBy('LiteralExpression'), CoveredBy('Expression'), Node], _IntegerDecs = [CoveredBy('LiteralExpression'), CoveredBy('Expression'), Node], _FloatDecs = [CoveredBy('LiteralExpression'), CoveredBy('Expression'), Node], "LiteralExpression")]() {
      yield eat(m`<_Any />`, [m`<True 'true' />`, m`<False 'false' />`, m`<Nil 'nil' />`, m`<Array '[' />`, m`<Object '{' />`, m`<String /['"]/ />`, m`<Integer /\d/ />`, m`<Float /[\d]+\.[\d]+/ />`]);
    }
    *True() {
      yield eat(m`sigilToken: <*Keyword 'true' />`);
    }
    *False() {
      yield eat(m`sigilToken: <*Keyword 'false' />`);
    }
    *Nil() {
      yield eat(m`sigilToken: <*Keyword 'nil' />`);
    }
    *Array() {
      yield eat(m`open: <*Punctuator '[' { balanced: ']' } />`);
      yield eat(m`elements[]+$: <_List />`, o({
        element: m`<__Expression />`,
        separator: m`separatorTokens[]: <*Punctuator ',' />`,
        allowTrailingSeparator: false
      }));
      yield eat(m`close: <*Punctuator ']' { balancer: true } />`);
    }
    *Object() {
      yield eat(m`open: <*Punctuator '{' { balanced: '}' } />`);
      yield eat(m`properties[]$: <_List />`, o({
        element: m`<Property />`,
        separator: m`separatorTokens[]: <*Punctuator ',' />`,
        allowTrailingSeparator: false
      }));
      yield eat(m`close: <*Punctuator '}' { balancer: true } />`);
    }
    *Property() {
      yield eat(m`key$: <Identifier />`);
      yield eat(m`mapOperator: <*Punctuator ':' />`);
      yield eat(m`value+$: <__Expression />`, o({
        power: 16
      }));
    }
    *String({
      ctx
    }) {
      let q = yield match(re`/['"]/`);
      if (!q) yield fail();
      const q_ = ctx.sourceTextFor(q);
      yield q_ === "'" ? eat(m`open: <*Punctuator "'" { balanced: "'", balancedSpan: 'String:Single' } />`) : eat(m`open: <*Punctuator '"' { balanced: '"', balancedSpan: 'String:Double' } />`);
      yield eat(m`content: <*StringContent />`);
      yield q_ === "'" ? eat(m`close: <*Punctuator "'" { balancer: true } />`) : eat(m`close: <*Punctuator '"' { balancer: true } />`);
    }
    *StringContent({
      state: {
        span
      }
    }) {
      let esc, lit;
      do {
        esc = (yield match('\\')) && (yield eat(m`@: <EscapeSequence />`));
        lit = span === 'String:Single' ? yield eatMatch(re`/[^\r\n\\']+/`) : yield eatMatch(re`/[^\r\n\\"]+/`);
      } while (esc || lit);
    }
    *EscapeSequence({
      state: {
        span
      },
      ctx
    }) {
      if (!span.startsWith('String')) {
        yield fail();
      }
      yield eat(m`escape: <*Punctuator '\\' { openSpan: 'Escape' } />`);
      let match;
      let cooked;
      if (match = span === 'String:Single' ? yield match(re`/[\\/nrt0']/`) : yield match(re`/[\\/nrt0"]/`)) {
        const match_ = ctx.sourceTextFor(match);
        yield eat(m`code: <*Keyword ${buildString(match_)} { closeSpan: 'Escape' } />`);
        cooked = escapables.get(match_) || match_;
      } else {
        let code = yield eat(m`code: <EscapeCode { closeSpan: 'Escape' } />`);
        cooked = String.fromCodePoint(parseInt(ctx.sourceTextFor(code.get('value')), 16));
      }
      yield defineAttribute('cooked', cooked);
    }
    *EscapeCode() {
      if (yield match('x')) {
        yield eatMatch(m`typeToken: <*Keyword 'x' />`);
        yield eat(m`digits[]: <Digits /\d{2}/ />`);
        yield eat(m`close: null`);
      } else if (yield match('u')) {
        yield eatMatch(m`typeToken: <*Keyword 'u' />`);
        yield eat(m`digits[]: <Digits /\d{4}/ />`);
        yield eat(m`close: null`);
      } else {
        yield fail();
      }
    }
    *Infinity() {
      yield eat(m`sigilToken: <*Keyword 'Infinity' />`);
    }
    *Integer({
      props: {
        noDoubleZero = false
      },
      ctx
    }) {
      let firstDigit = ctx.sourceTextFor(yield eat(re`/\d/`));
      if (!noDoubleZero || firstDigit.value !== '0') {
        yield eatMatch(re`/\d+/`);
      }
    }
    *Float() {
      yield eat(m`wholePart$: <*Integer />`, o({
        noDoubleZero: true
      }));
      let fs = yield eatMatch(m`fractionalSeparatorToken: <*Punctuator '.' />`, null, o({
        bind: true
      }));
      if (fs) {
        yield eat(m`fractionalPart$: <*Integer />`);
      } else {
        yield eat(m`fractionalPart$: null`);
      }
    }
  };
};