/* @macrome
 * @generatedby @bablr/macrome-generator-bablr
 * @generatedfrom ./statement.macro.js#30e0f7f479539297de0010950a3b5cbd650323d7
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import _applyDecs from "@babel/runtime/helpers/applyDecs2305";
import { re, spam as m } from '@bablr/boot';
import { eat, match, eatMatch, fail, o } from '@bablr/helpers/grammar';
import { AllowEmpty, CoveredBy, InjectFrom, Node } from '@bablr/helpers/decorators';
import * as productions from '@bablr/helpers/productions';
import { ReferenceTag } from '@bablr/agast-helpers/symbols';
export const mixin = Base => {
  let _initProto, _ExpressionStatementDecs, _FunctionStatementDecs, _ReturnStatementDecs, _ThrowStatementDecs, _LocalVariableWriteDecs, _BlockStatementDecs, _IfStatementDecs, _WhileStatementDecs, _DoWhileStatementDecs, _SwitchStatementDecs, _ForStatementDecs, _ForInStatementDecs, _LabeledStatementDecs, _BreakStatementDecs, _ContinueStatementDecs, _PunctuatorDecs;
  return class RubyStatementGrammar extends Base {
    static {
      [_initProto] = _applyDecs(this, [[[Node, AllowEmpty], 2, "Statements"], [_ExpressionStatementDecs, 2, "ExpressionStatement"], [_FunctionStatementDecs, 2, "FunctionStatement"], [_ReturnStatementDecs, 2, "ReturnStatement"], [_ThrowStatementDecs, 2, "ThrowStatement"], [_LocalVariableWriteDecs, 2, "LocalVariableWrite"], [Node, 2, "VariableDeclarator"], [_BlockStatementDecs, 2, "BlockStatement"], [_IfStatementDecs, 2, "IfStatement"], [_WhileStatementDecs, 2, "WhileStatement"], [_DoWhileStatementDecs, 2, "DoWhileStatement"], [_SwitchStatementDecs, 2, "SwitchStatement"], [Node, 2, "SwitchCase"], [_ForStatementDecs, 2, "ForStatement"], [_ForInStatementDecs, 2, "ForInStatement"], [_LabeledStatementDecs, 2, "LabeledStatement"], [_BreakStatementDecs, 2, "BreakStatement"], [_ContinueStatementDecs, 2, "ContinueStatement"], [_PunctuatorDecs, 2, "Punctuator"]], [], 0, void 0, Base).e;
    }
    constructor(...args) {
      super(...args);
      _initProto(this);
    }
    *[(_ExpressionStatementDecs = [CoveredBy('Statement'), Node], _FunctionStatementDecs = [CoveredBy('Statement'), Node], _ReturnStatementDecs = [CoveredBy('Statement'), Node], _ThrowStatementDecs = [CoveredBy('Statement'), Node], _LocalVariableWriteDecs = [CoveredBy('Statement'), Node], _BlockStatementDecs = [CoveredBy('Statement'), Node], _IfStatementDecs = [CoveredBy('Statement'), Node], _WhileStatementDecs = [CoveredBy('Statement'), Node], _DoWhileStatementDecs = [CoveredBy('Statement'), Node], _SwitchStatementDecs = [CoveredBy('Statement'), Node], _ForStatementDecs = [CoveredBy('LoopStatement'), CoveredBy('Statement'), Node], _ForInStatementDecs = [CoveredBy('LoopStatement'), CoveredBy('Statement'), Node], _LabeledStatementDecs = [CoveredBy('Statement'), Node], _BreakStatementDecs = [CoveredBy('Statement'), Node], _ContinueStatementDecs = [CoveredBy('Statement'), Node], _PunctuatorDecs = [Node, InjectFrom(productions)], "Statements")]({
      ctx,
      s
    }) {
      let stmt, trivia, newline;
      while (yield match(re`/./s`)) {
        stmt = yield eat(m`body[]+: <__Statement />`);
        if (s.resultPath?.previousSibling.tag.type === ReferenceTag && s.resultPath?.previousSibling.tag.value.type === '#') {
          trivia = s.resultPath.inner;
        } else {
          trivia = yield eatMatch(m`#: <_Space /[\n\r;]/ />`);
        }
        newline = trivia && ctx.sourceTextFor(trivia).includes('\n');
        if (!(stmt.get('endToken') || newline)) break;
      }
    }
    *Statement() {
      yield eat(m`<_Any />`, [m`<BlockStatement '|' />`, m`<IfStatement 'if' />`, m`<WhileStatement 'while' />`, m`<DoWhileStatement 'do' />`, m`<SwitchStatement 'switch' />`, m`<_LoopStatement 'for' />`, m`<FunctionStatement /function [a-zA-Z$_]/ />`, m`<ReturnStatement 'return' />`, m`<ThrowStatement 'throw' />`, m`<ExpressionStatement />`]);
    }
    *ExpressionStatement() {
      yield eat(m`expression+: <__Expression />`);
    }
    *FunctionStatement() {
      yield eat(m`sigilToken: <*Keyword 'function' />`);
      yield eat(m`id: <Identifier />`);
      yield eat(m`openArgumentsToken: <*Punctuator '(' { balanced: ')' } />`);
      yield eat(m`params[]: <_List />`, o({
        element: m`<Identifier />`,
        allowTrailingSeparator: false,
        separator: m`separatorTokens[]: <*Punctuator ',' />`
      }));
      yield eat(m`closeArgumentsToken: <*Punctuator ')' { balancer: true } />`);
      yield eat(m`body: <BlockStatement />`);
    }
    *ReturnStatement() {
      yield eat(m`sigilToken: <*Keyword 'return' />`);
      yield eat(m`expression+$: <__Expression />`);
    }
    *ThrowStatement() {
      yield eat(m`sigilToken: <*Keyword 'throw' />`);
      yield eat(m`expression+$: <__Expression />`);
    }
    *LocalVariableWrite() {
      yield eat(m`declarations[]: <VariableDeclarator />`);
      yield eat(m`declarations[]: <_List />`, o({
        element: m`<VariableDeclarator />`,
        allowTrailingSeparator: false,
        separator: m`separatorTokens[]: <*Punctuator ',' />`
      }));
    }
    *VariableDeclarator() {
      yield eat(m`id: <Identifier />`);
      yield eat(m`sigilToken: <*Punctuator '=' />`);
      yield eat(m`init: <*Statement />`);
    }
    *BlockStatement() {
      yield eat(m`openToken: <*Punctuator '|' { balanced: '|' } />`);
      yield eat(m`body[]: <_StatementList />`);
      yield eat(m`closeToken: <*Punctuator '|' { balancer: true } />`);
    }
    *IfStatement() {
      yield eat(m`sigilToken: <*Keyword 'if' />`);
      yield eat(m`openHeaderToken: <*Punctuator '(' { balanced: ')' } />`);
      yield eat(m`test: <__Expression />`);
      yield eat(m`closeHeaderToken: <*Punctuator ')' { balancer: true } />`);
      yield eat(m`consequent: <__Statement />`, o({
        allowEmpty: false
      }));
      if (yield eatMatch(m`alternateSigilToken: <*Keyword 'else' />`)) {
        yield eat(m`consequent: <__Statement />`, o({
          allowEmpty: false
        }));
      } else {
        yield eat(m`alternate: null`);
      }
    }
    *WhileStatement() {
      yield eat(m`sigilToken: <*Keyword 'while' />`);
      yield eat(m`openHeaderToken: <*Punctuator '(' { balanced: ')' } />`);
      yield eat(m`test+$: <__Expression />`);
      yield eat(m`closeHeaderToken: <*Punctuator ')' { balancer: true } />`);
      yield eat(m`body: <__Statement />`);
    }
    *DoWhileStatement() {
      yield eat(m`sigilToken: <*Keyword 'do' />`);
      yield eat(m`body: <__Statement />`);
      yield eat(m`footerSigilToken: <*Keyword 'while' />`);
      yield eat(m`openFooterToken: <*Punctuator '(' { balanced: ')' } />`);
      yield eat(m`test+$: <__Expression />`);
      yield eat(m`closeFooterToken: <*Punctuator ')' { balancer: true } />`);
    }
    *SwitchStatement() {
      yield eat(m`sigilToken: <*Keyword 'switch' />`);
      yield eat(m`openDiscriminantToken: <*Punctuator '(' { balanced: ')' } />`);
      yield eat(m`discriminant+$: <__Expression />`);
      yield eat(m`closeDiscriminantToken: <*Punctuator ')' { balancer: true } />`);
      yield eat(m`openCasesToken: <*Punctuator '{' { balanced: '}' } />`);
      yield eatMatch(m`cases[]: <SwitchCase /(case|default)\b/ />`);
      yield eat(m`closeCasesToken: <*Punctuator '}' { balancer: true } />`);
    }
    *SwitchCase({
      intrinsicValue,
      ctx
    }) {
      switch (ctx.sourceTextFor(intrinsicValue)) {
        case 'case':
          yield eat(m`sigilToken: <*Keyword 'case' />`);
          yield eat(m`condition+$: <__Expression />`);
          break;
        case 'default':
          yield eat(m`sigilToken: <*Keyword 'default' />`);
          yield eat(m`condition: null`);
          break;
        default:
          yield fail();
          break;
      }
      yield eat(m`bodySeparatorToken: <*Punctuator ':' />`);
      while (yield match(re`/./`)) yield eat(m`statements[]: <__Statement />`);
    }
    *LoopStatement() {
      // This might have been called ForStatement, but that name was already in use
      throw new Error('not implemented');
    }
    *ForStatement() {
      yield eat(m`sigilToken: <*Keyword 'for' />`);
      yield eat(m`openHeaderToken: <*Punctuator '(' { balanced: ')' } />`);
      if (!(yield eatMatch(m`init: <VariableDeclaration />`))) {
        yield eatMatch(m`init+$: <__Expression />`);
      }
      yield eat(m`testSeparatorToken: <*Punctuator ';' />`);
      yield eatMatch(m`test+$: <__Expression />`);
      yield eat(m`updateSeparatorToken: <*Punctuator ';' />`);
      yield eatMatch(m`update+$: <__Expression />`);
      yield eat(m`closeHeaderToken: <*Punctuator ')' { balancer: true } />`);
      yield eat(m`body: <__Statement />`);
    }
    *ForInStatement() {
      yield eat(m`sigilToken: <*Keyword 'for' />`);
      yield eat(m`openHeaderToken: <*Punctuator '(' { balanced: ')' } />`);
      if (!(yield eatMatch(m`left: <VariableDeclaration />`))) {
        yield eatMatch(m`left: <__Expression />`);
      }
      yield eat(m`iterationSigilToken: <*Keyword 'in' />`);
      yield eatMatch(m`right+$: <__Expression />`);
      yield eat(m`closeHeaderToken: <*Punctuator ')' { balancer: true } />`);
      yield eat(m`body: <__Statement />`);
    }
    *LabeledStatement() {
      yield eat(m`label: <Identifier />`);
      yield eat(m`sigilToken: <*Puncuator ':' />`);
      yield eat(m`body: <*Statement />`);
    }
    *BreakStatement() {
      yield eat(m`sigilToken: <*Keyword 'break' />`);
      yield eatMatch(m`label: <Identifier />`);
    }
    *ContinueStatement() {
      yield eat(m`sigilToken: <*Keyword 'continue' />`);
      yield eatMatch(m`label: <Identifier />`);
    }
    *Punctuator() {}
  };
};